# Student ID: 111522071

## HW 4-1

In [1]:
#import package
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold
from sklearn import ensemble, metrics
from sklearn.metrics import accuracy_score
from sklearn.utils import shuffle
import math

In [2]:
# Read CSV
dataset = pd.read_csv("train.csv")

In [3]:
#將dataset shuffle
dataset = shuffle(dataset)
label = dataset.label
dataset = dataset[:-1]

In [37]:
#svm
#Import library
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
from numpy import random

#10-fold cross-validation
kfold = KFold(10)
predicted = []
expected = []
svm = OneVsRestClassifier(SVC(gamma='scale'))
#Train model
for train,valid in kfold.split(dataset):
    X_train = dataset.iloc[train]
    Y_train = label.iloc[train]

    X_valid = dataset.iloc[valid]
    Y_valid = label.iloc[valid]

    svm.fit(X_train,Y_train)
    expected.extend(Y_valid)
    predicted.extend(svm.predict(X_valid))

# test
rand_int = random.randint(0,1741,10) # 0~1741 選10筆

X_test = dataset.iloc[rand_int]
Y_test = label.iloc[rand_int]

SVM_expected_test = Y_test
SVM_predicted_test = svm.predict(X_test)

In [38]:
print("SVM_expected_test = {}".format(SVM_expected_test.values))
print("SVM_predicted_test = {}".format(SVM_predicted_test))

SVM_expected_test = [5 7 0 7 0 5 4 0 4 0]
SVM_predicted_test = [5 7 0 7 0 5 4 0 4 0]


In [40]:
# print("Macro-average: {0}".format(metrics.f1_score(expected,predicted,average='macro')))
# print("Micro-average: {0}".format(metrics.f1_score(expected,predicted,average='micro')))
def print_acc(expected,predicted):
    print(metrics.classification_report(expected,predicted))
    print(metrics.confusion_matrix(expected, predicted))
    accuracy = accuracy_score(expected, predicted)
    print("Accuracy: %.2f%%" % (accuracy * 100.0))

    # print("Average = macro")
    print('precision:',metrics.precision_score(expected, predicted,average='macro')) 
    print('recall:',metrics.recall_score(expected, predicted,average='macro'))
    print('F1-score:',metrics.f1_score(expected, predicted,average='macro'))

# print("\n")
# print("Average = micro")
# print('precision:', metrics.precision_score(expected, predicted, average='micro')) 
# print('recall:',metrics.recall_score(expected, predicted,average='micro'))
# print('F1-score:',metrics.f1_score(expected, predicted,labels=[0,1,2,3,4,5,6,7],average='micro'))

# print("\n")
# print("Average = weighted")
# print('precision:', metrics.precision_score(expected, predicted, average='weighted'))
# print('recall:',metrics.recall_score(expected, predicted,average='micro'))
# print('F1-score:',metrics.f1_score(expected,predicted,labels=[0,1,2,3,4,5,6,7],average='weighted'))

In [41]:
print_acc(SVM_expected_test,SVM_predicted_test)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           4       1.00      1.00      1.00         2
           5       1.00      1.00      1.00         2
           7       1.00      1.00      1.00         2

    accuracy                           1.00        10
   macro avg       1.00      1.00      1.00        10
weighted avg       1.00      1.00      1.00        10

[[4 0 0 0]
 [0 2 0 0]
 [0 0 2 0]
 [0 0 0 2]]
Accuracy: 100.00%
precision: 1.0
recall: 1.0
F1-score: 1.0


## HW 4-2

In [42]:
#ramdom forest
#Import library
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from numpy import random

#10-fold cross-validation
kfold = KFold(10)
predicted = []
expected = []
forest = RandomForestClassifier(n_estimators = 100)
#Train model
for train,valid in kfold.split(dataset):
    X_train = dataset.iloc[train]
    Y_train = label.iloc[train]

    X_valid = dataset.iloc[valid]
    Y_valid = label.iloc[valid]

    forest.fit(X_train,Y_train)
    expected.extend(Y_valid)
    predicted.extend(forest.predict(X_valid))

# test
rand_int = random.randint(0,1741,10) # 0~1741 選10筆

X_test = dataset.iloc[rand_int]
Y_test = label.iloc[rand_int]

forest_expected_test = Y_test
forest_predicted_test = forest.predict(X_test)

In [43]:
print("forest_expected_test = {}".format(forest_expected_test.values))
print("forest_predicted_test = {}".format(forest_predicted_test))

forest_expected_test = [5 5 3 7 2 4 7 6 3 4]
forest_predicted_test = [5 5 3 7 2 4 7 6 3 4]


In [44]:
print_acc(forest_expected_test,forest_predicted_test)

              precision    recall  f1-score   support

           2       1.00      1.00      1.00         1
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         2
           5       1.00      1.00      1.00         2
           6       1.00      1.00      1.00         1
           7       1.00      1.00      1.00         2

    accuracy                           1.00        10
   macro avg       1.00      1.00      1.00        10
weighted avg       1.00      1.00      1.00        10

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 2]]
Accuracy: 100.00%
precision: 1.0
recall: 1.0
F1-score: 1.0
