In [2]:
import numpy as np

In [3]:
from numpy import random

In [4]:
#輸入np array
data = np.array([9,2,3,4,10,6,7,8,1,5])
data

array([ 9,  2,  3,  4, 10,  6,  7,  8,  1,  5])

In [6]:
#輸入計算出array維度與元素數量
print('Dimension:',data.ndim)
print('Number of elements:',data.size)

Dimension: 1
Number of elements: 10


In [7]:
import numpy as np
data = np.array([9,2,3,4,10,6,7,8,1,5])
print('data*2',data*2)
print('乘法運算：',np.array([1,2,3,4,5,6,7,8,9,9]*np.array([10,9,8,7,6,5,4,3,2,1])))
print('連乘：',data**2)
print('除法：',np.array([1,2,3,4,5,6,7,8,9,9]/np.array([10,9,8,7,6,5,4,3,2,1])))

data*2 [18  4  6  8 20 12 14 16  2 10]
乘法運算： [10 18 24 28 30 30 28 24 18  9]
連乘： [ 81   4   9  16 100  36  49  64   1  25]
除法： [0.1        0.22222222 0.375      0.57142857 0.83333333 1.2
 1.75       2.66666667 4.5        9.        ]


In [9]:
#array值排序
data.sort()
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
#array最小值、最大值、總和、累積和、累積比例
print(data.min())
print(data.max())
print(data.sum())
print(data.cumsum())

1
10
55
[ 1  3  6 10 15 21 28 36 45 55]


In [14]:
#產生亂數
random.seed(0)

random.randn(10)

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

In [15]:
#顯示到小數點後第三位
%precision 3

'%.3f'

In [17]:
data = np.array([9,2,3,4,10,6,7,8,1,5])

# 隨機取出
# 取出10個(允許重複，放回抽樣)
print(random.choice(data,10))
#  取出10個(不允許重複，不放回抽樣)
print(random.choice(data,10,replace=False))

[ 7  8  8  1  2  6  5  1  5 10]
[10  2  7  8  3  1  6  5  9  4]


In [18]:
#產生矩陣
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#矩陣運算
輸入程式碼

In [20]:
#製作元素為0或1的矩陣
print(np.zeros((2,3),dtype = np.int64))
print(np.ones((2,3),dtype = np.int64))

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
